export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';

export const INCREMENT_QUANTITY_PRODUCT = 'INCREMENT_QUANTITY_PRODUCT';

export const DECREMENT_QUANTITY_PRODUCT = 'DECREMENT_QUANTITY_PRODUCT';

export const RESET_PRODUCTS = 'RESET_PRODUCTS';

export const SET_COMMENTS = 'SET_COMMENTS';